[package]
name = "vec_key_value_pair"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Ciubix8513/vec_key_value_pair"
license ="Apache-2.0"
description = "A drop-in replacement for std::HashMap that uses Vec on the backend"
readme="Readme.md"
